baseURL = 'https://akn.yt/'
languageCode = 'en-us'
title = 'Jeriakn'
publishDir = "public"

[params]
  description = ""

[outputs]
  home = ["HTML"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
